DEFAULT_FOLDER = nusp/rev1
SERIAL_DRIVER = vendor
#DYNAMIC_KEYMAP_ENABLE = yes

#OLED_ENABLE = yes
#OLED_DRIVER = ssd1306
#OLED_TRANSPORT = i2c

#POINTING_DEVICE_ENABLE = yes
#POINTING_DEVICE_DRIVER = custom
#JOYSTICK_ENABLE = yes
#JOYSTICK_DRIVER = analog

#OPT_DEFS += -DHAL_USE_I2C=TRUE

#SRC += drivers/sensors/analog_joystick.c
#SRC += sub_joystick.c